name: Build Safinity APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: 🔧 Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: 🧰 Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            zip unzip openjdk-11-jdk git python3-pip \
            libpng-dev libjpeg-dev libfreetype6-dev \
            zlib1g-dev python3-dev libgl1-mesa-dev libgles2-mesa-dev m4


      - name: Install build dependencies
        run: |
           sudo apt-get update
           sudo apt-get install -y autoconf libtool automake m4
 
      - name: Install dependencies
        run: |
           sudo apt-get update
           sudo apt-get install -y \
             automake \
             autoconf \
             libtool \
             libltdl-dev \
             libffi-dev \
             build-essential \
             pkg-config     

      - name: 📦 Install Buildozer
        run: |
          pip install --upgrade pip
          pip install cython==0.29.36 buildozer==1.5.0

      - name: ✅ Ensure buildozer.spec Exists
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Create ~/.safinity/user_data.json with dummy user
        run: |
          mkdir -p ~/.safinity
          echo '[
            {
              "email": "f2021376083@umt.edu.pk",
              "phone_number": "+923336507022",
              "password": "alpha123",
              "country": "Pakistan",
              "created_at": "2025-03-15 00:26:42.738115"
            }
          ]' > ~/.safinity/user_data.json

      - name: 📂 Scan project for missing dependencies or Python errors
        shell: bash
        run: |
          echo "📂 Scanning project files for suspicious error messages..."
          grep -riE "ImportError|ModuleNotFoundError|No module named|FileNotFoundError|cannot import name" . || echo "✅ No suspicious error patterns found."

          echo "🔎 Checking Python files for syntax errors..."
          find . -name "*.py" -exec python3 -m py_compile {} \; || echo "⚠️ Some files have syntax errors."

          echo "🧪 Checking for broken or missing dependencies via pip..."
          pip check || echo "⚠️ pip check reported some issues."

          echo "🧹 (Optional) Linting with flake8..."
          pip install flake8
          flake8 . || echo "⚠️ flake8 found style or import issues."

      - name: 📲 Build APK
        run: buildozer android debug --log_level=2

      - name: 📤 Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Safinity-APK
          path: bin/*.apk

      - name: 📲 Check APK
        run: buildozer android logcat

      - name: 🐛 Analyze Build Log for Crash Clues
        run: |
          echo "------ 🔍 Possible Errors in Build Log ------"
          grep -iE "error|exception|traceback" ./.buildozer/android/platform/build-*/build.log || echo "No obvious errors found"

      - name: 🤖 Start Android Emulator and Run App
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          script: |
            echo "📱 Installing APK..."
            adb install ./bin/*.apk

            echo "🚀 Launching Kivy App..."
            adb shell am start -n org.safinity.app/com.kivy.android.PythonActivity

            echo "⏱️ Waiting for 10 seconds to let it run..."
            sleep 10

            echo "📦 Capturing Logcat Output..."
            adb logcat -d > logcat_output.txt
            tail -n 100 logcat_output.txt
